package com.eagleeye.salary.eo;
// default package
// Generated 2011-12-9 14:14:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SalaryConfigOwner generated by hbm2java
 */
@Entity
@Table(name = "salary_config_owner", catalog = "eagleeye")
public class SalaryConfigOwnerEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2245322779461387369L;
	private SalaryConfigOwnerEOId id;
	private String templateName;

	public SalaryConfigOwnerEO() {
	}

	public SalaryConfigOwnerEO(SalaryConfigOwnerEOId id, String templateName) {
		this.id = id;
		this.templateName = templateName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "staffId", column = @Column(name = "staff_id", nullable = false, length = 100)) })
	public SalaryConfigOwnerEOId getId() {
		return this.id;
	}

	public void setId(SalaryConfigOwnerEOId id) {
		this.id = id;
	}

	@Column(name = "template_name", nullable = false, length = 100)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

}
