package com.eagleeye.salary.eo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalarySettlementId generated by hbm2java
 */
@Embeddable
public class SalarySettlementEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4586617493133447815L;
	private String managerId;
	private String staffId;
	private Date start;
	private Date end;

	public SalarySettlementEOId() {
	}

	public SalarySettlementEOId(String managerId, String staffId, Date start,
			Date end) {
		this.managerId = managerId;
		this.staffId = staffId;
		this.start = start;
		this.end = end;
	}

	@Column(name = "manager_id", nullable = false, length = 100)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "staff_id", nullable = false, length = 100)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "start", nullable = false, length = 0)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Column(name = "end", nullable = false, length = 0)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalarySettlementEOId))
			return false;
		SalarySettlementEOId castOther = (SalarySettlementEOId) other;

		return ((this.getManagerId() == castOther.getManagerId()) || (this
				.getManagerId() != null
				&& castOther.getManagerId() != null && this.getManagerId()
				.equals(castOther.getManagerId())))
				&& ((this.getStaffId() == castOther.getStaffId()) || (this
						.getStaffId() != null
						&& castOther.getStaffId() != null && this.getStaffId()
						.equals(castOther.getStaffId())))
				&& ((this.getStart() == castOther.getStart()) || (this
						.getStart() != null
						&& castOther.getStart() != null && this.getStart()
						.equals(castOther.getStart())))
				&& ((this.getEnd() == castOther.getEnd()) || (this.getEnd() != null
						&& castOther.getEnd() != null && this.getEnd().equals(
						castOther.getEnd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getManagerId() == null ? 0 : this.getManagerId().hashCode());
		result = 37 * result
				+ (getStaffId() == null ? 0 : this.getStaffId().hashCode());
		result = 37 * result
				+ (getStart() == null ? 0 : this.getStart().hashCode());
		result = 37 * result
				+ (getEnd() == null ? 0 : this.getEnd().hashCode());
		return result;
	}

}
