package com.eagleeye.salary.eo;
// default package
// Generated 2011-12-9 14:14:54 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalaryConfigOwnerId generated by hbm2java
 */
@Embeddable
public class SalaryConfigOwnerEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1250564265450844228L;
	private String managerId;
	private String staffId;

	public SalaryConfigOwnerEOId() {
	}

	public SalaryConfigOwnerEOId(String managerId, String staffId) {
		this.managerId = managerId;
		this.staffId = staffId;
	}

	@Column(name = "manager_id", nullable = false, length = 100)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "staff_id", nullable = false, length = 100)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalaryConfigOwnerEOId))
			return false;
		SalaryConfigOwnerEOId castOther = (SalaryConfigOwnerEOId) other;

		return ((this.getManagerId() == castOther.getManagerId()) || (this
				.getManagerId() != null && castOther.getManagerId() != null && this
				.getManagerId().equals(castOther.getManagerId())))
				&& ((this.getStaffId() == castOther.getStaffId()) || (this
						.getStaffId() != null && castOther.getStaffId() != null && this
						.getStaffId().equals(castOther.getStaffId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getManagerId() == null ? 0 : this.getManagerId().hashCode());
		result = 37 * result
				+ (getStaffId() == null ? 0 : this.getStaffId().hashCode());
		return result;
	}

}
