package com.eagleeye.salary.eo;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalarySettlement generated by hbm2java
 */
@Entity
@Table(name = "salary_settlement", catalog = "eagleeye")
public class SalarySettlementEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7843044508071169967L;
	private SalarySettlementEOId id;
	private BigDecimal baseSalary = BigDecimal.ZERO;
	private String settlementType;
	private Boolean achieveTarget = false;
	private BigDecimal baseRateResult = BigDecimal.ZERO;
	private BigDecimal extraRateResult = BigDecimal.ZERO;
	private BigDecimal plusAmountResult = BigDecimal.ZERO;
	private BigDecimal subtractAmountResult = BigDecimal.ZERO;
	private BigDecimal topSaleAmountPlusResult = BigDecimal.ZERO;
	private BigDecimal topAvgReplyPlusResult = BigDecimal.ZERO;
	private BigDecimal topTotalReplyPlusResult = BigDecimal.ZERO;
	private BigDecimal topExchangeRatePlusResult = BigDecimal.ZERO;
	private BigDecimal topManBuyPlusResult = BigDecimal.ZERO;
	private BigDecimal zeroRefundPlusResult = BigDecimal.ZERO;
	private BigDecimal lastAvgReplySubtractResult = BigDecimal.ZERO;
	private BigDecimal lastTotalReplySubtractResult = BigDecimal.ZERO;
	private BigDecimal lastSaleAmountSubtractResult = BigDecimal.ZERO;
	private BigDecimal lastExchangeRateSubtractResult = BigDecimal.ZERO;
	private BigDecimal topRefundAmountSubtractResult = BigDecimal.ZERO;
	private BigDecimal adjustAmount = BigDecimal.ZERO;
	private BigDecimal finalSalaryResult = BigDecimal.ZERO;
	private Date settlementDate = new Date();

	public SalarySettlementEO() {
	}

	public SalarySettlementEO(SalarySettlementEOId id) {
		this.id = id;
	}

	public SalarySettlementEO(SalarySettlementEOId id, BigDecimal baseSalary,
			String settlementType, Boolean achieveTarget,
			BigDecimal baseRateResult, BigDecimal extraRateResult,
			BigDecimal plusAmountResult, BigDecimal subtractAmountResult,
			BigDecimal topSaleAmountPlusResult,
			BigDecimal topAvgReplyPlusResult,
			BigDecimal topTotalReplyPlusResult,
			BigDecimal topExchangeRatePlusResult,
			BigDecimal topManBuyPlusResult, BigDecimal zeroRefundPlusResult,
			BigDecimal lastAvgReplySubtractResult,
			BigDecimal lastTotalReplySubtractResult,
			BigDecimal lastSaleAmountSubtractResult,
			BigDecimal lastExchangeRateSubtractResult,
			BigDecimal topRefundAmountSubtractResult,
			BigDecimal finalSalaryResult, Date settlementDate) {
		this.id = id;
		this.baseSalary = baseSalary;
		this.settlementType = settlementType;
		this.achieveTarget = achieveTarget;
		this.baseRateResult = baseRateResult;
		this.extraRateResult = extraRateResult;
		this.plusAmountResult = plusAmountResult;
		this.subtractAmountResult = subtractAmountResult;
		this.topSaleAmountPlusResult = topSaleAmountPlusResult;
		this.topAvgReplyPlusResult = topAvgReplyPlusResult;
		this.topTotalReplyPlusResult = topTotalReplyPlusResult;
		this.topExchangeRatePlusResult = topExchangeRatePlusResult;
		this.topManBuyPlusResult = topManBuyPlusResult;
		this.zeroRefundPlusResult = zeroRefundPlusResult;
		this.lastAvgReplySubtractResult = lastAvgReplySubtractResult;
		this.lastTotalReplySubtractResult = lastTotalReplySubtractResult;
		this.lastSaleAmountSubtractResult = lastSaleAmountSubtractResult;
		this.lastExchangeRateSubtractResult = lastExchangeRateSubtractResult;
		this.topRefundAmountSubtractResult = topRefundAmountSubtractResult;
		this.finalSalaryResult = finalSalaryResult;
		this.settlementDate = settlementDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "staffId", column = @Column(name = "staff_id", nullable = false, length = 100)),
			@AttributeOverride(name = "start", column = @Column(name = "start", nullable = false, length = 0)),
			@AttributeOverride(name = "end", column = @Column(name = "end", nullable = false, length = 0)) })
	public SalarySettlementEOId getId() {
		return this.id;
	}

	public void setId(SalarySettlementEOId id) {
		this.id = id;
	}

	@Column(name = "base_salary", precision = 10)
	public BigDecimal getBaseSalary() {
		return this.baseSalary;
	}

	public void setBaseSalary(BigDecimal baseSalary) {
		this.baseSalary = baseSalary;
	}

	@Column(name = "settlement_type", length = 2)
	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	@Column(name = "achieve_target")
	public Boolean getAchieveTarget() {
		return this.achieveTarget;
	}

	public void setAchieveTarget(Boolean achieveTarget) {
		this.achieveTarget = achieveTarget;
	}

	@Column(name = "base_rate_result", precision = 10)
	public BigDecimal getBaseRateResult() {
		return this.baseRateResult;
	}

	public void setBaseRateResult(BigDecimal baseRateResult) {
		this.baseRateResult = baseRateResult;
	}

	@Column(name = "extra_rate_result", precision = 10)
	public BigDecimal getExtraRateResult() {
		return this.extraRateResult;
	}

	public void setExtraRateResult(BigDecimal extraRateResult) {
		this.extraRateResult = extraRateResult;
	}

	@Column(name = "plus_amount_result", precision = 10)
	public BigDecimal getPlusAmountResult() {
		return this.plusAmountResult;
	}

	public void setPlusAmountResult(BigDecimal plusAmountResult) {
		this.plusAmountResult = plusAmountResult;
	}

	@Column(name = "subtract_amount_result", precision = 10)
	public BigDecimal getSubtractAmountResult() {
		return this.subtractAmountResult;
	}

	public void setSubtractAmountResult(BigDecimal subtractAmountResult) {
		this.subtractAmountResult = subtractAmountResult;
	}

	@Column(name = "top_sale_amount_plus_result", precision = 10)
	public BigDecimal getTopSaleAmountPlusResult() {
		return this.topSaleAmountPlusResult;
	}

	public void setTopSaleAmountPlusResult(BigDecimal topSaleAmountPlusResult) {
		this.topSaleAmountPlusResult = topSaleAmountPlusResult;
	}

	@Column(name = "top_avg_reply_plus_result", precision = 10)
	public BigDecimal getTopAvgReplyPlusResult() {
		return this.topAvgReplyPlusResult;
	}

	public void setTopAvgReplyPlusResult(BigDecimal topAvgReplyPlusResult) {
		this.topAvgReplyPlusResult = topAvgReplyPlusResult;
	}

	@Column(name = "top_total_reply_plus_result", precision = 10)
	public BigDecimal getTopTotalReplyPlusResult() {
		return this.topTotalReplyPlusResult;
	}

	public void setTopTotalReplyPlusResult(BigDecimal topTotalReplyPlusResult) {
		this.topTotalReplyPlusResult = topTotalReplyPlusResult;
	}

	@Column(name = "top_exchange_rate_plus_result", precision = 10)
	public BigDecimal getTopExchangeRatePlusResult() {
		return this.topExchangeRatePlusResult;
	}

	public void setTopExchangeRatePlusResult(
			BigDecimal topExchangeRatePlusResult) {
		this.topExchangeRatePlusResult = topExchangeRatePlusResult;
	}

	@Column(name = "top_man_buy_plus_result", precision = 10)
	public BigDecimal getTopManBuyPlusResult() {
		return this.topManBuyPlusResult;
	}

	public void setTopManBuyPlusResult(BigDecimal topManBuyPlusResult) {
		this.topManBuyPlusResult = topManBuyPlusResult;
	}

	@Column(name = "zero_refund_plus_result", precision = 10)
	public BigDecimal getZeroRefundPlusResult() {
		return this.zeroRefundPlusResult;
	}

	public void setZeroRefundPlusResult(BigDecimal zeroRefundPlusResult) {
		this.zeroRefundPlusResult = zeroRefundPlusResult;
	}

	@Column(name = "last_avg_reply_subtract_result", precision = 10)
	public BigDecimal getLastAvgReplySubtractResult() {
		return this.lastAvgReplySubtractResult;
	}

	public void setLastAvgReplySubtractResult(
			BigDecimal lastAvgReplySubtractResult) {
		this.lastAvgReplySubtractResult = lastAvgReplySubtractResult;
	}

	@Column(name = "last_total_reply_subtract_result", precision = 10)
	public BigDecimal getLastTotalReplySubtractResult() {
		return this.lastTotalReplySubtractResult;
	}

	public void setLastTotalReplySubtractResult(
			BigDecimal lastTotalReplySubtractResult) {
		this.lastTotalReplySubtractResult = lastTotalReplySubtractResult;
	}

	@Column(name = "last_sale_amount_subtract_result", precision = 10)
	public BigDecimal getLastSaleAmountSubtractResult() {
		return this.lastSaleAmountSubtractResult;
	}

	public void setLastSaleAmountSubtractResult(
			BigDecimal lastSaleAmountSubtractResult) {
		this.lastSaleAmountSubtractResult = lastSaleAmountSubtractResult;
	}

	@Column(name = "last_exchange_rate_subtract_result", precision = 10)
	public BigDecimal getLastExchangeRateSubtractResult() {
		return this.lastExchangeRateSubtractResult;
	}

	public void setLastExchangeRateSubtractResult(
			BigDecimal lastExchangeRateSubtractResult) {
		this.lastExchangeRateSubtractResult = lastExchangeRateSubtractResult;
	}

	@Column(name = "top_refund_amount_subtract_result", precision = 10)
	public BigDecimal getTopRefundAmountSubtractResult() {
		return this.topRefundAmountSubtractResult;
	}

	public void setTopRefundAmountSubtractResult(
			BigDecimal topRefundAmountSubtractResult) {
		this.topRefundAmountSubtractResult = topRefundAmountSubtractResult;
	}

	@Column(name = "final_salary_result", precision = 10)
	public BigDecimal getFinalSalaryResult() {
		return this.finalSalaryResult;
	}

	public void setFinalSalaryResult(BigDecimal finalSalaryResult) {
		this.finalSalaryResult = finalSalaryResult;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "settlement_date", length = 0)
	public Date getSettlementDate() {
		return this.settlementDate;
	}

	public void setSettlementDate(Date settlementDate) {
		this.settlementDate = settlementDate;
	}

	@Column(name = "adjust_amount", precision = 10)
	public BigDecimal getAdjustAmount() {
		return adjustAmount;
	}

	public void setAdjustAmount(BigDecimal adjustAmount) {
		this.adjustAmount = adjustAmount;
	}
}
