package com.eagleeye.salary.eo;

// default package
// Generated 2011-12-3 9:17:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * SalaryConfig generated by hbm2java
 */
@Entity
@Table(name = "salary_config", catalog = "eagleeye")
public class SalaryConfigEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5444793252183702519L;
	private SalaryConfigEOId id;
	private BigDecimal baseSalary = BigDecimal.ZERO;
	private String settlementType = "1";
	private BigDecimal achievementAmountTarget = BigDecimal.ZERO;
	private BigDecimal amountBaseRate = BigDecimal.ZERO;
	private BigDecimal amountExtraRate = BigDecimal.ZERO;
	private BigDecimal achievementNumTarget = BigDecimal.ZERO;
	private BigDecimal numBaseRate = BigDecimal.ZERO;
	private BigDecimal numExtraRate = BigDecimal.ZERO;
	private BigDecimal topSaleAmountPlus = BigDecimal.ZERO;
	private BigDecimal topAvgReplyPlus = BigDecimal.ZERO;
	private BigDecimal topTotalReplyPlus = BigDecimal.ZERO;
	private BigDecimal topExchangeRatePlus = BigDecimal.ZERO;
	private BigDecimal topManBuyPlus = BigDecimal.ZERO;
	private BigDecimal zeroRefundPlus = BigDecimal.ZERO;
	private BigDecimal lastAvgReplySubtract = BigDecimal.ZERO;
	private BigDecimal lastTotalReplySubtract = BigDecimal.ZERO;
	private BigDecimal lastSaleAmountSubtract = BigDecimal.ZERO;
	private BigDecimal lastExchangeRateSubtract = BigDecimal.ZERO;
	private BigDecimal topRefundAmountSubtract = BigDecimal.ZERO;
	private Boolean noManagerFlg = false;

	public SalaryConfigEO() {
	}

	public SalaryConfigEO(SalaryConfigEOId id) {
		this.id = id;
	}

	public SalaryConfigEO(SalaryConfigEOId id, BigDecimal baseSalary,
			String settlementType, BigDecimal achievementAmountTarget,
			BigDecimal amountBaseRate, BigDecimal amountExtraRate,
			BigDecimal achievementNumTarget, BigDecimal numBaseRate,
			BigDecimal numExtraRate, BigDecimal topSaleAmountPlus,
			BigDecimal topAvgReplyPlus, BigDecimal topTotalReplyPlus,
			BigDecimal topExchangeRatePlus, BigDecimal topManBuyPlus,
			BigDecimal zeroRefundPlus, BigDecimal lastAvgReplySubtract,
			BigDecimal lastTotalReplySubtract,
			BigDecimal lastSaleAmountSubtract,
			BigDecimal lastExchangeRateSubtract,
			BigDecimal topRefundAmountSubtract) {
		this.id = id;
		this.baseSalary = baseSalary;
		this.settlementType = settlementType;
		this.achievementAmountTarget = achievementAmountTarget;
		this.amountBaseRate = amountBaseRate;
		this.amountExtraRate = amountExtraRate;
		this.achievementNumTarget = achievementNumTarget;
		this.numBaseRate = numBaseRate;
		this.numExtraRate = numExtraRate;
		this.topSaleAmountPlus = topSaleAmountPlus;
		this.topAvgReplyPlus = topAvgReplyPlus;
		this.topTotalReplyPlus = topTotalReplyPlus;
		this.topExchangeRatePlus = topExchangeRatePlus;
		this.topManBuyPlus = topManBuyPlus;
		this.zeroRefundPlus = zeroRefundPlus;
		this.lastAvgReplySubtract = lastAvgReplySubtract;
		this.lastTotalReplySubtract = lastTotalReplySubtract;
		this.lastSaleAmountSubtract = lastSaleAmountSubtract;
		this.lastExchangeRateSubtract = lastExchangeRateSubtract;
		this.topRefundAmountSubtract = topRefundAmountSubtract;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "templateName", column = @Column(name = "template_name", nullable = false, length = 100)) })
	public SalaryConfigEOId getId() {
		return this.id;
	}

	public void setId(SalaryConfigEOId id) {
		this.id = id;
	}

	@Column(name = "base_salary", precision = 10)
	public BigDecimal getBaseSalary() {
		return this.baseSalary;
	}

	public void setBaseSalary(BigDecimal baseSalary) {
		this.baseSalary = baseSalary;
	}

	@Column(name = "settlement_type", length = 2)
	public String getSettlementType() {
		return this.settlementType;
	}

	public void setSettlementType(String settlementType) {
		this.settlementType = settlementType;
	}

	@Column(name = "achievement_amount_target", precision = 10)
	public BigDecimal getAchievementAmountTarget() {
		return this.achievementAmountTarget;
	}

	public void setAchievementAmountTarget(BigDecimal achievementAmountTarget) {
		this.achievementAmountTarget = achievementAmountTarget;
	}

	@Column(name = "amount_base_rate", precision = 8, scale = 6)
	public BigDecimal getAmountBaseRate() {
		return this.amountBaseRate;
	}

	public void setAmountBaseRate(BigDecimal amountBaseRate) {
		this.amountBaseRate = amountBaseRate;
	}

	@Column(name = "amount_extra_rate", precision = 8, scale = 6)
	public BigDecimal getAmountExtraRate() {
		return this.amountExtraRate;
	}

	public void setAmountExtraRate(BigDecimal amountExtraRate) {
		this.amountExtraRate = amountExtraRate;
	}

	@Column(name = "achievement_num_target", precision = 10)
	public BigDecimal getAchievementNumTarget() {
		return this.achievementNumTarget;
	}

	public void setAchievementNumTarget(BigDecimal achievementNumTarget) {
		this.achievementNumTarget = achievementNumTarget;
	}

	@Column(name = "num_base_rate", precision = 10)
	public BigDecimal getNumBaseRate() {
		return this.numBaseRate;
	}

	public void setNumBaseRate(BigDecimal numBaseRate) {
		this.numBaseRate = numBaseRate;
	}

	@Column(name = "num_extra_rate", precision = 10)
	public BigDecimal getNumExtraRate() {
		return this.numExtraRate;
	}

	public void setNumExtraRate(BigDecimal numExtraRate) {
		this.numExtraRate = numExtraRate;
	}

	@Column(name = "top_sale_amount_plus", precision = 10)
	public BigDecimal getTopSaleAmountPlus() {
		return this.topSaleAmountPlus;
	}

	public void setTopSaleAmountPlus(BigDecimal topSaleAmountPlus) {
		this.topSaleAmountPlus = topSaleAmountPlus;
	}

	@Column(name = "top_avg_reply_plus", precision = 10)
	public BigDecimal getTopAvgReplyPlus() {
		return this.topAvgReplyPlus;
	}

	public void setTopAvgReplyPlus(BigDecimal topAvgReplyPlus) {
		this.topAvgReplyPlus = topAvgReplyPlus;
	}

	@Column(name = "top_total_reply_plus", precision = 10)
	public BigDecimal getTopTotalReplyPlus() {
		return this.topTotalReplyPlus;
	}

	public void setTopTotalReplyPlus(BigDecimal topTotalReplyPlus) {
		this.topTotalReplyPlus = topTotalReplyPlus;
	}

	@Column(name = "top_exchange_rate_plus", precision = 10)
	public BigDecimal getTopExchangeRatePlus() {
		return this.topExchangeRatePlus;
	}

	public void setTopExchangeRatePlus(BigDecimal topExchangeRatePlus) {
		this.topExchangeRatePlus = topExchangeRatePlus;
	}

	@Column(name = "top_man_buy_plus", precision = 10)
	public BigDecimal getTopManBuyPlus() {
		return this.topManBuyPlus;
	}

	public void setTopManBuyPlus(BigDecimal topManBuyPlus) {
		this.topManBuyPlus = topManBuyPlus;
	}

	@Column(name = "zero_refund_plus", precision = 10)
	public BigDecimal getZeroRefundPlus() {
		return this.zeroRefundPlus;
	}

	public void setZeroRefundPlus(BigDecimal zeroRefundPlus) {
		this.zeroRefundPlus = zeroRefundPlus;
	}

	@Column(name = "last_avg_reply_subtract", precision = 10)
	public BigDecimal getLastAvgReplySubtract() {
		return this.lastAvgReplySubtract;
	}

	public void setLastAvgReplySubtract(BigDecimal lastAvgReplySubtract) {
		this.lastAvgReplySubtract = lastAvgReplySubtract;
	}

	@Column(name = "last_total_reply_subtract", precision = 10)
	public BigDecimal getLastTotalReplySubtract() {
		return this.lastTotalReplySubtract;
	}

	public void setLastTotalReplySubtract(BigDecimal lastTotalReplySubtract) {
		this.lastTotalReplySubtract = lastTotalReplySubtract;
	}

	@Column(name = "last_sale_amount_subtract", precision = 10)
	public BigDecimal getLastSaleAmountSubtract() {
		return this.lastSaleAmountSubtract;
	}

	public void setLastSaleAmountSubtract(BigDecimal lastSaleAmountSubtract) {
		this.lastSaleAmountSubtract = lastSaleAmountSubtract;
	}

	@Column(name = "last_exchange_rate_subtract", precision = 10)
	public BigDecimal getLastExchangeRateSubtract() {
		return this.lastExchangeRateSubtract;
	}

	public void setLastExchangeRateSubtract(BigDecimal lastExchangeRateSubtract) {
		this.lastExchangeRateSubtract = lastExchangeRateSubtract;
	}

	@Column(name = "top_refund_amount_subtract", precision = 10)
	public BigDecimal getTopRefundAmountSubtract() {
		return this.topRefundAmountSubtract;
	}

	public void setTopRefundAmountSubtract(BigDecimal topRefundAmountSubtract) {
		this.topRefundAmountSubtract = topRefundAmountSubtract;
	}

	@Transient
	public Boolean getNoManagerFlg() {
		return noManagerFlg;
	}

	public void setNoManagerFlg(Boolean noManagerFlg) {
		this.noManagerFlg = noManagerFlg;
	}

}
