package com.eagleeye.eservice.eo;

// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatPeerId generated by hbm2java
 */
@Embeddable
public class ChatPeerEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7037549475319249548L;
	private String serviceStaffId;
	private String uid;
	private Date chatDate;

	public ChatPeerEOId() {
	}

	public ChatPeerEOId(String serviceStaffId, String uid, Date chatDate) {
		this.serviceStaffId = serviceStaffId;
		this.uid = uid;
		this.chatDate = chatDate;
	}

	@Column(name = "service_staff_id", nullable = false, length = 100)
	public String getServiceStaffId() {
		return this.serviceStaffId;
	}

	public void setServiceStaffId(String serviceStaffId) {
		this.serviceStaffId = serviceStaffId;
	}

	@Column(name = "uid", nullable = false, length = 100)
	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Column(name = "chat_date", nullable = false, length = 0)
	public Date getChatDate() {
		return this.chatDate;
	}

	public void setChatDate(Date chatDate) {
		this.chatDate = chatDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChatPeerEOId))
			return false;
		ChatPeerEOId castOther = (ChatPeerEOId) other;

		return ((this.getServiceStaffId() == castOther.getServiceStaffId()) || (this
				.getServiceStaffId() != null
				&& castOther.getServiceStaffId() != null && this
				.getServiceStaffId().equals(castOther.getServiceStaffId())))
				&& ((this.getUid() == castOther.getUid()) || (this.getUid() != null
						&& castOther.getUid() != null && this.getUid().equals(
						castOther.getUid())))
				&& ((this.getChatDate() == castOther.getChatDate()) || (this
						.getChatDate() != null
						&& castOther.getChatDate() != null && this
						.getChatDate().equals(castOther.getChatDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceStaffId() == null ? 0 : this.getServiceStaffId()
						.hashCode());
		result = 37 * result
				+ (getUid() == null ? 0 : this.getUid().hashCode());
		result = 37 * result
				+ (getChatDate() == null ? 0 : this.getChatDate().hashCode());
		return result;
	}

}
