package com.eagleeye.eservice.eo;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChatPeer generated by hbm2java
 */
@Entity
@Table(name = "chat_peer", catalog = "eagleeye")
public class ChatPeerEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8837937206502293822L;
	private ChatPeerEOId id;
	private Date createdAt;

	public ChatPeerEO() {
	}

	public ChatPeerEO(ChatPeerEOId id, Date createdAt) {
		this.id = id;
		this.createdAt = createdAt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serviceStaffId", column = @Column(name = "service_staff_id", nullable = false, length = 100)),
			@AttributeOverride(name = "uid", column = @Column(name = "uid", nullable = false, length = 100)),
			@AttributeOverride(name = "chatDate", column = @Column(name = "chat_date", nullable = false, length = 0)) })
	public ChatPeerEOId getId() {
		return this.id;
	}

	public void setId(ChatPeerEOId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 0)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
}
