package com.eagleeye.eservice.eo;

// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NonReplyStatOnDay generated by hbm2java
 */
@Entity
@Table(name = "non_reply_stat_on_day", catalog = "eagleeye")
public class NonReplyStatOnDayEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6762873411279485401L;
	private NonReplyStatOnDayEOId id;
	private long nonReplyNum;
	private Date createdAt;
	private Date updatedAt;
	private String managerId;

	public NonReplyStatOnDayEO() {
	}

	public NonReplyStatOnDayEO(NonReplyStatOnDayEOId id, long nonReplyNum,
			Date createdAt, Date updatedAt, String managerId) {
		this.id = id;
		this.nonReplyNum = nonReplyNum;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.managerId = managerId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serviceStaffId", column = @Column(name = "service_staff_id", nullable = false, length = 100)),
			@AttributeOverride(name = "nonreplyDate", column = @Column(name = "nonreply_date", nullable = false, length = 0)) })
	public NonReplyStatOnDayEOId getId() {
		return this.id;
	}

	public void setId(NonReplyStatOnDayEOId id) {
		this.id = id;
	}

	@Column(name = "non_reply_num", nullable = false)
	public long getNonReplyNum() {
		return this.nonReplyNum;
	}

	public void setNonReplyNum(long nonReplyNum) {
		this.nonReplyNum = nonReplyNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 0)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 0)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "manager_id", nullable = false, length = 100)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

}
