package com.eagleeye.eservice.eo;
// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OnlineTimesOnDayId generated by hbm2java
 */
@Embeddable
public class OnlineTimesOnDayEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5390663255863002800L;
	private String serviceStaffId;
	private Date onlineDate;

	public OnlineTimesOnDayEOId() {
	}

	public OnlineTimesOnDayEOId(String serviceStaffId, Date onlineDate) {
		this.serviceStaffId = serviceStaffId;
		this.onlineDate = onlineDate;
	}

	@Column(name = "service_staff_id", nullable = false, length = 100)
	public String getServiceStaffId() {
		return this.serviceStaffId;
	}

	public void setServiceStaffId(String serviceStaffId) {
		this.serviceStaffId = serviceStaffId;
	}

	@Column(name = "online_date", nullable = false, length = 0)
	public Date getOnlineDate() {
		return this.onlineDate;
	}

	public void setOnlineDate(Date onlineDate) {
		this.onlineDate = onlineDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OnlineTimesOnDayEOId))
			return false;
		OnlineTimesOnDayEOId castOther = (OnlineTimesOnDayEOId) other;

		return ((this.getServiceStaffId() == castOther.getServiceStaffId()) || (this
				.getServiceStaffId() != null
				&& castOther.getServiceStaffId() != null && this
				.getServiceStaffId().equals(castOther.getServiceStaffId())))
				&& ((this.getOnlineDate() == castOther.getOnlineDate()) || (this
						.getOnlineDate() != null
						&& castOther.getOnlineDate() != null && this
						.getOnlineDate().equals(castOther.getOnlineDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceStaffId() == null ? 0 : this.getServiceStaffId()
						.hashCode());
		result = 37
				* result
				+ (getOnlineDate() == null ? 0 : this.getOnlineDate()
						.hashCode());
		return result;
	}

}
