package com.eagleeye.eservice.eo;
// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReplyStatOnDayId generated by hbm2java
 */
@Embeddable
public class ReplyStatOnDayEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8229193851706453007L;
	private String serviceStaffId;
	private Date replyDate;

	public ReplyStatOnDayEOId() {
	}

	public ReplyStatOnDayEOId(String serviceStaffId, Date replyDate) {
		this.serviceStaffId = serviceStaffId;
		this.replyDate = replyDate;
	}

	@Column(name = "service_staff_id", nullable = false, length = 100)
	public String getServiceStaffId() {
		return this.serviceStaffId;
	}

	public void setServiceStaffId(String serviceStaffId) {
		this.serviceStaffId = serviceStaffId;
	}

	@Column(name = "reply_date", nullable = false, length = 0)
	public Date getReplyDate() {
		return this.replyDate;
	}

	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReplyStatOnDayEOId))
			return false;
		ReplyStatOnDayEOId castOther = (ReplyStatOnDayEOId) other;

		return ((this.getServiceStaffId() == castOther.getServiceStaffId()) || (this
				.getServiceStaffId() != null
				&& castOther.getServiceStaffId() != null && this
				.getServiceStaffId().equals(castOther.getServiceStaffId())))
				&& ((this.getReplyDate() == castOther.getReplyDate()) || (this
						.getReplyDate() != null
						&& castOther.getReplyDate() != null && this
						.getReplyDate().equals(castOther.getReplyDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceStaffId() == null ? 0 : this.getServiceStaffId()
						.hashCode());
		result = 37 * result
				+ (getReplyDate() == null ? 0 : this.getReplyDate().hashCode());
		return result;
	}

}
