package com.eagleeye.eservice.eo;
// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StaffEvalStatOnDay generated by hbm2java
 */
@Entity
@Table(name = "staff_eval_stat_on_day", catalog = "eagleeye")
public class StaffEvalStatOnDayEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7296235887688039902L;
	private StaffEvalStatOnDayEOId id;
	private String evaluationName;
	private int evaluationNum;
	private Date createdAt;
	private Date updatedAt;

	public StaffEvalStatOnDayEO() {
	}

	public StaffEvalStatOnDayEO(StaffEvalStatOnDayEOId id, String evaluationName,
			int evaluationNum, Date createdAt, Date updatedAt) {
		this.id = id;
		this.evaluationName = evaluationName;
		this.evaluationNum = evaluationNum;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "serviceStaffId", column = @Column(name = "service_staff_id", nullable = false, length = 100)),
			@AttributeOverride(name = "evalDate", column = @Column(name = "eval_date", nullable = false, length = 0)) })
	public StaffEvalStatOnDayEOId getId() {
		return this.id;
	}

	public void setId(StaffEvalStatOnDayEOId id) {
		this.id = id;
	}

	@Column(name = "evaluation_name", nullable = false)
	public String getEvaluationName() {
		return this.evaluationName;
	}

	public void setEvaluationName(String evaluationName) {
		this.evaluationName = evaluationName;
	}

	@Column(name = "evaluation_num", nullable = false)
	public int getEvaluationNum() {
		return this.evaluationNum;
	}

	public void setEvaluationNum(int evaluationNum) {
		this.evaluationNum = evaluationNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 0)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 0)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
