package com.eagleeye.eservice.eo;
// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StaffEvalStatOnDayId generated by hbm2java
 */
@Embeddable
public class StaffEvalStatOnDayEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7975276498168542627L;
	private String serviceStaffId;
	private Date evalDate;

	public StaffEvalStatOnDayEOId() {
	}

	public StaffEvalStatOnDayEOId(String serviceStaffId, Date evalDate) {
		this.serviceStaffId = serviceStaffId;
		this.evalDate = evalDate;
	}

	@Column(name = "service_staff_id", nullable = false, length = 100)
	public String getServiceStaffId() {
		return this.serviceStaffId;
	}

	public void setServiceStaffId(String serviceStaffId) {
		this.serviceStaffId = serviceStaffId;
	}

	@Column(name = "eval_date", nullable = false, length = 0)
	public Date getEvalDate() {
		return this.evalDate;
	}

	public void setEvalDate(Date evalDate) {
		this.evalDate = evalDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StaffEvalStatOnDayEOId))
			return false;
		StaffEvalStatOnDayEOId castOther = (StaffEvalStatOnDayEOId) other;

		return ((this.getServiceStaffId() == castOther.getServiceStaffId()) || (this
				.getServiceStaffId() != null
				&& castOther.getServiceStaffId() != null && this
				.getServiceStaffId().equals(castOther.getServiceStaffId())))
				&& ((this.getEvalDate() == castOther.getEvalDate()) || (this
						.getEvalDate() != null
						&& castOther.getEvalDate() != null && this
						.getEvalDate().equals(castOther.getEvalDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceStaffId() == null ? 0 : this.getServiceStaffId()
						.hashCode());
		result = 37 * result
				+ (getEvalDate() == null ? 0 : this.getEvalDate().hashCode());
		return result;
	}

}
