package com.eagleeye.eservice.eo;
// default package
// Generated 2011-12-13 16:46:38 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TradeRateId generated by hbm2java
 */
@Embeddable
public class TradeRateEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7758264458472630740L;
	private long tid;
	private long oid;

	public TradeRateEOId() {
	}

	public TradeRateEOId(long tid, long oid) {
		this.tid = tid;
		this.oid = oid;
	}

	@Column(name = "tid", nullable = false)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "oid", nullable = false)
	public long getOid() {
		return this.oid;
	}

	public void setOid(long oid) {
		this.oid = oid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeRateEOId))
			return false;
		TradeRateEOId castOther = (TradeRateEOId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getOid() == castOther.getOid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTid();
		result = 37 * result + (int) this.getOid();
		return result;
	}

}
