package com.eagleeye.eservice.eo;

// default package
// Generated 2011-12-13 16:46:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.eagleeye.common.constant.EagleConstants;
import com.eagleeye.schedule.constant.ScheduleConstants;

/**
 * TradeRate generated by hbm2java
 */
@Entity
@Table(name = "trade_rate", catalog = "eagleeye")
public class TradeRateEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2662001034528803635L;
	private TradeRateEOId id;
	private Boolean validScore;
	private String nick;
	private String result;
	private Date created;
	private String ratedNick;
	private String itemTitle;
	private String content;
	private String reply;
	private String chatLogStatus = ScheduleConstants.SCHEDULE_INIT_STATUS;
	private String owner = EagleConstants.NO_OWNER;
	private Boolean isSalary = true;

	public TradeRateEO() {
	}

	public TradeRateEO(TradeRateEOId id) {
		this.id = id;
	}

	public TradeRateEO(TradeRateEOId id, Boolean validScore, String nick,
			String result, Date created, String ratedNick, String itemTitle,
			String content, String reply) {
		this.id = id;
		this.validScore = validScore;
		this.nick = nick;
		this.result = result;
		this.created = created;
		this.ratedNick = ratedNick;
		this.itemTitle = itemTitle;
		this.content = content;
		this.reply = reply;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tid", column = @Column(name = "tid", nullable = false)),
			@AttributeOverride(name = "oid", column = @Column(name = "oid", nullable = false)) })
	public TradeRateEOId getId() {
		return this.id;
	}

	public void setId(TradeRateEOId id) {
		this.id = id;
	}

	@Column(name = "valid_score")
	public Boolean getValidScore() {
		return this.validScore;
	}

	public void setValidScore(Boolean validScore) {
		this.validScore = validScore;
	}

	@Column(name = "nick", length = 100)
	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	@Column(name = "result", length = 8)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "rated_nick", length = 100)
	public String getRatedNick() {
		return this.ratedNick;
	}

	public void setRatedNick(String ratedNick) {
		this.ratedNick = ratedNick;
	}

	@Column(name = "item_title")
	public String getItemTitle() {
		return this.itemTitle;
	}

	public void setItemTitle(String itemTitle) {
		this.itemTitle = itemTitle;
	}

	@Column(name = "content", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "reply", length = 1000)
	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	@Column(name = "chat_log_status", length = 1)
	public String getChatLogStatus() {
		return chatLogStatus;
	}

	public void setChatLogStatus(String chatLogStatus) {
		this.chatLogStatus = chatLogStatus;
	}

	@Column(name = "is_salary", length = 1)
	public Boolean getIsSalary() {
		return isSalary;
	}

	public void setIsSalary(Boolean isSalary) {
		this.isSalary = isSalary;
	}

	@Column(name = "owner", length = 1)
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

}
