package com.eagleeye.nopayclean.eo;

// default package
// Generated 2011-12-23 17:46:39 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NoPayCleanDetail generated by hbm2java
 */
@Entity
@Table(name = "no_pay_clean_detail", catalog = "eagleeye")
public class NoPayCleanDetailEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2792371173421938789L;
	private NoPayCleanDetailEOId id;
	private String status;
	private Date deadLine;

	public NoPayCleanDetailEO() {
	}

	public NoPayCleanDetailEO(NoPayCleanDetailEOId id) {
		this.id = id;
	}

	public NoPayCleanDetailEO(NoPayCleanDetailEOId id, String status) {
		this.id = id;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", nullable = false, length = 0)) })
	public NoPayCleanDetailEOId getId() {
		return this.id;
	}

	public void setId(NoPayCleanDetailEOId id) {
		this.id = id;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "deadline", length = 0)
	public Date getDeadLine() {
		return deadLine;
	}

	public void setDeadLine(Date deadLine) {
		this.deadLine = deadLine;
	}

}
