package com.eagleeye.user.eo;

// default package
// Generated 2011-11-19 12:12:31 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupMember generated by hbm2java
 */
@Entity
@Table(name = "group_member", catalog = "eagleeye")
public class GroupMemberEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7750696545199159218L;
	private GroupMemberEOId id;
	private String groupName;
	private String shopId;
	private Date createdAt;
	private Date updatedAt;
	private Long flag;

	public GroupMemberEO() {
	}

	public GroupMemberEO(GroupMemberEOId id, String groupName, String shopId,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.groupName = groupName;
		this.shopId = shopId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "serviceStaffId", column = @Column(name = "service_staff_id", nullable = false, length = 100)),
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)) })
	public GroupMemberEOId getId() {
		return this.id;
	}

	public void setId(GroupMemberEOId id) {
		this.id = id;
	}

	@Column(name = "group_name", nullable = false, length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "shop_id", nullable = false, length = 36)
	public String getShopId() {
		return this.shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 0)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_at", nullable = false, length = 0)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "flag", nullable = true)
	public Long getFlag() {
		return flag;
	}

	public void setFlag(Long flag) {
		this.flag = flag;
	}

}
