package com.eagleeye.user.eo;

// Generated 2012-8-18 21:57:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReadLockMapping generated by hbm2java
 */
@Entity
@Table(name = "read_lock_mapping", catalog = "eagleeye")
public class ReadLockMappingEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7539710730041237974L;
	private ReadLockMappingEOId id;
	private String menuName;
	private Date creatDate;

	public ReadLockMappingEO() {
	}

	public ReadLockMappingEO(ReadLockMappingEOId id) {
		this.id = id;
	}

	public ReadLockMappingEO(ReadLockMappingEOId id, Date creatDate) {
		this.id = id;
		this.creatDate = creatDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "readLockUrl", column = @Column(name = "read_lock_url", nullable = false, length = 100)) })
	public ReadLockMappingEOId getId() {
		return this.id;
	}

	public void setId(ReadLockMappingEOId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_date", length = 0)
	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	@Column(name = "menu_name", nullable = false, length = 100)
	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}
}
