package com.eagleeye.statistics.eo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StatAchievementNumId generated by hbm2java
 */
@Embeddable
public class StatAchievementNumEOId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3680990155235922414L;
	/**
	 * 
	 */
	private String managerId;
	private boolean isTotal;
	private Date statDate;
	private String staffId;

	public StatAchievementNumEOId() {
	}

	public StatAchievementNumEOId(String managerId, boolean isTotal,
			Date statDate, String staffId) {
		this.managerId = managerId;
		this.isTotal = isTotal;
		this.statDate = statDate;
		this.staffId = staffId;
	}

	@Column(name = "manager_id", nullable = false, length = 100)
	public String getManagerId() {
		return this.managerId;
	}

	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	@Column(name = "is_total", nullable = false)
	public boolean isIsTotal() {
		return this.isTotal;
	}

	public void setIsTotal(boolean isTotal) {
		this.isTotal = isTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "stat_date", nullable = false, length = 0)
	public Date getStatDate() {
		return this.statDate;
	}

	public void setStatDate(Date statDate) {
		this.statDate = statDate;
	}

	@Column(name = "staff_id", nullable = false, length = 100)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StatAchievementNumEOId))
			return false;
		StatAchievementNumEOId castOther = (StatAchievementNumEOId) other;

		return ((this.getManagerId() == castOther.getManagerId()) || (this
				.getManagerId() != null
				&& castOther.getManagerId() != null && this.getManagerId()
				.equals(castOther.getManagerId())))
				&& (this.isIsTotal() == castOther.isIsTotal())
				&& ((this.getStatDate() == castOther.getStatDate()) || (this
						.getStatDate() != null
						&& castOther.getStatDate() != null && this
						.getStatDate().equals(castOther.getStatDate())))
				&& ((this.getStaffId() == castOther.getStaffId()) || (this
						.getStaffId() != null
						&& castOther.getStaffId() != null && this.getStaffId()
						.equals(castOther.getStaffId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getManagerId() == null ? 0 : this.getManagerId().hashCode());
		result = 37 * result + (this.isIsTotal() ? 1 : 0);
		result = 37 * result
				+ (getStatDate() == null ? 0 : this.getStatDate().hashCode());
		result = 37 * result
				+ (getStaffId() == null ? 0 : this.getStaffId().hashCode());
		return result;
	}

}
