package com.eagleeye.statistics.eo;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StatAchievementNum generated by hbm2java
 */
@Entity
@Table(name = "stat_achievement_num", catalog = "eagleeye")
public class StatAchievementNumEO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8587085526633212234L;
	/**
	 * 
	 */
	private StatAchievementNumEOId id;
	private BigDecimal numWaitSend = BigDecimal.ZERO;
	private BigDecimal numWaitConfirm = BigDecimal.ZERO;
	private BigDecimal numSuccess = BigDecimal.ZERO;
	private BigDecimal numRefunding = BigDecimal.ZERO;
	private BigDecimal numAllRefund = BigDecimal.ZERO;
	private BigDecimal numPartRefund = BigDecimal.ZERO;
	private BigDecimal totalNumNoRefund = BigDecimal.ZERO;
	private BigDecimal totalNumHasRefund = BigDecimal.ZERO;

	public StatAchievementNumEO() {
	}

	public StatAchievementNumEO(StatAchievementNumEOId id) {
		this.id = id;
	}

	public StatAchievementNumEO(StatAchievementNumEOId id,
			BigDecimal numWaitSend, BigDecimal numWaitConfirm,
			BigDecimal numSuccess, BigDecimal numRefunding,
			BigDecimal numAllRefund, BigDecimal numPartRefund,
			BigDecimal totalNumNoRefund, BigDecimal totalNumHasRefund) {
		this.id = id;
		this.numWaitSend = numWaitSend;
		this.numWaitConfirm = numWaitConfirm;
		this.numSuccess = numSuccess;
		this.numRefunding = numRefunding;
		this.numAllRefund = numAllRefund;
		this.numPartRefund = numPartRefund;
		this.totalNumNoRefund = totalNumNoRefund;
		this.totalNumHasRefund = totalNumHasRefund;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "managerId", column = @Column(name = "manager_id", nullable = false, length = 100)),
			@AttributeOverride(name = "isTotal", column = @Column(name = "is_total", nullable = false)),
			@AttributeOverride(name = "statDate", column = @Column(name = "stat_date", nullable = false, length = 0)),
			@AttributeOverride(name = "staffId", column = @Column(name = "staff_id", nullable = false, length = 100)) })
	public StatAchievementNumEOId getId() {
		return this.id;
	}

	public void setId(StatAchievementNumEOId id) {
		this.id = id;
	}

	@Column(name = "num_wait_send", precision = 10, scale = 0)
	public BigDecimal getNumWaitSend() {
		return this.numWaitSend;
	}

	public void setNumWaitSend(BigDecimal numWaitSend) {
		this.numWaitSend = numWaitSend;
	}

	@Column(name = "num_wait_confirm", precision = 10, scale = 0)
	public BigDecimal getNumWaitConfirm() {
		return this.numWaitConfirm;
	}

	public void setNumWaitConfirm(BigDecimal numWaitConfirm) {
		this.numWaitConfirm = numWaitConfirm;
	}

	@Column(name = "num_success", precision = 10, scale = 0)
	public BigDecimal getNumSuccess() {
		return this.numSuccess;
	}

	public void setNumSuccess(BigDecimal numSuccess) {
		this.numSuccess = numSuccess;
	}

	@Column(name = "num_refunding", precision = 10, scale = 0)
	public BigDecimal getNumRefunding() {
		return this.numRefunding;
	}

	public void setNumRefunding(BigDecimal numRefunding) {
		this.numRefunding = numRefunding;
	}

	@Column(name = "num_all_refund", precision = 10, scale = 0)
	public BigDecimal getNumAllRefund() {
		return this.numAllRefund;
	}

	public void setNumAllRefund(BigDecimal numAllRefund) {
		this.numAllRefund = numAllRefund;
	}

	@Column(name = "num_part_refund", precision = 10, scale = 0)
	public BigDecimal getNumPartRefund() {
		return this.numPartRefund;
	}

	public void setNumPartRefund(BigDecimal numPartRefund) {
		this.numPartRefund = numPartRefund;
	}

	@Column(name = "total_num_no_refund", precision = 10, scale = 0)
	public BigDecimal getTotalNumNoRefund() {
		return this.totalNumNoRefund;
	}

	public void setTotalNumNoRefund(BigDecimal totalNumNoRefund) {
		this.totalNumNoRefund = totalNumNoRefund;
	}

	@Column(name = "total_num_has_refund", precision = 10, scale = 0)
	public BigDecimal getTotalNumHasRefund() {
		return this.totalNumHasRefund;
	}

	public void setTotalNumHasRefund(BigDecimal totalNumHasRefund) {
		this.totalNumHasRefund = totalNumHasRefund;
	}

}
